### ISSUE TITLE
Need to update the Learn QGIS documentation to be accurate for QGIS 3

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-learn-qgis#3]
### Content Suggestion ###

The documentation needs to be updated for QGIS 3.  QGIS 2 examples should only be kept if substantial and relevant.  There is probably not a need to keep version 2 content except for installer (since there is some history there for the GeoProcessor) but other sections are not that substantial so can start focusing on QGIS 3.  **The installer sections are up to date for QGIS 3 but other sections need version 3 screen shots, etc.**

**Comment by egiles16** [comment]
Updated the install/uninstall instructions for QGIS3.

**Comment by smalers** [comment]
I updated the documentation to be current for QGIS 3.4.3.  Close this issue.
